# This zshrc requires oh-my-zsh to be installed
export ZSH=$HOME/.oh-my-zsh
export ZSH_CUSTOM=~/.custom-oh-my-zsh

# DISABLE_AUTO_TITLE="true"
ENABLE_CORRECTION="true" # Uncomment this line to enable command auto-correction.
COMPLETION_WAITING_DOTS="true" # Uncomment this line to display red dots whilst waiting for completion.

#zaf is a custom aliases and function plugin
plugins=(gitfast fasd web-search virtualenvwrapper screen rvm python node npm dirhistory zaf)
#ZSH_THEME="fletcherm"
#ZSH_THEME="nanotech"
ZSH_THEME="spranesh"

source $ZSH/oh-my-zsh.sh

# User configuration
PATH="/bin:/usr/local/bin:/usr/local/sbin/:/usr/bin:/sbin:/usr/local/sbin/:/usr/games:/usr/local/games"
PATH_ADDITIONS="~/bin:~/.rvm/bin"
export PATH=${PATH}:${PATH_ADDITIONS}

export EDITOR=vim
export LANG=en_US.UTF-8

# source ~/.zsh-aliases-functions
